# Generated by Django 2.2.5 on 2019-09-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=20)),
                ('complaint_title', models.CharField(max_length=30)),
                ('complaint_details', models.CharField(max_length=100)),
            ],
        ),
    ]
