# Generated by Django 2.2.5 on 2019-10-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Police', '0002_mostwanted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missing',
            name='image',
            field=models.ImageField(upload_to='missing_people'),
        ),
        migrations.AlterField(
            model_name='mostwanted',
            name='dob',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mostwanted',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='wanted_people'),
        ),
    ]
