# Generated by Django 2.2.5 on 2019-10-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Police', '0005_auto_20191026_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mostwanted',
            old_name='eyes',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='mostwanted',
            old_name='hair',
            new_name='crime_area',
        ),
        migrations.RenameField(
            model_name='mostwanted',
            old_name='race',
            new_name='crime_spot',
        ),
        migrations.RenameField(
            model_name='mostwanted',
            old_name='sex',
            new_name='crime_type',
        ),
        migrations.RemoveField(
            model_name='mostwanted',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='mostwanted',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='mostwanted',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mostwanted',
            name='weight',
        ),
        migrations.AddField(
            model_name='mostwanted',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mostwanted',
            name='photo',
            field=models.ImageField(blank=True, upload_to='wanted_people'),
        ),
        migrations.AlterField(
            model_name='mostwanted',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
