# Generated by Django 2.2.5 on 2019-10-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Police', '0006_auto_20191026_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mostwanted',
            old_name='name',
            new_name='uname',
        ),
    ]
