# Generated by Django 2.2.5 on 2019-10-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Police', '0007_auto_20191026_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='wanted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('height', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=20)),
                ('crime_type', models.CharField(max_length=20)),
                ('crime_area', models.CharField(max_length=20)),
                ('crime_spot', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='wanted_people')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
