# Generated by Django 2.2.5 on 2019-10-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Police', '0008_wanted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mostwanted',
        ),
        migrations.AlterField(
            model_name='missing',
            name='image',
            field=models.ImageField(blank=True, upload_to='missing_people'),
        ),
        migrations.AlterField(
            model_name='missing',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wanted',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='wanted_people'),
        ),
    ]
